# Generated by Django 4.2.1 on 2023-05-21 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 0, 27, 2, 304426), verbose_name='Data da compra'),
        ),
    ]
