# Generated by Django 4.2.1 on 2023-08-08 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_user_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 8, 9, 28, 37, 816239), verbose_name='Data da compra'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.FloatField(max_length=10),
        ),
    ]
